Module 10
juasmartinezbelS4N/nodejs_course pull request #10
Opened 2024-05-20 18:34 UTC by juasmartinezbelS4N

2024-05-21 05:59 UTC, MinMiguelM commented
Please let me know when it is completed, thanks!

2024-05-23 16:02 UTC, MinMiguelM requested changes
One small change, almost done!

2024-05-23 16:02 UTC, MinMiguelM commented on src/module_10/database/mongoDB.ts
>    const uri: string = `mongodb://localhost:${process.env.DB_PORT}`
Host should be in a env variable

2024-05-23 16:36 UTC, juasmartinezbelS4N commented on src/module_10/database/mongoDB.ts
>    const uri: string = `mongodb://localhost:${process.env.DB_PORT}`
I DON'T KNOW HOW I MISSED THIS, THANK YOU!

2024-05-23 17:51 UTC, MinMiguelM approved these changes
Well done

2024-05-23 18:01 UTC, merged